language: node_js
node_js:
  - 12.13.1

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm ci

before_script:
  - npm start -- --silent &

script:
  - npm run lint
  - npm run test:e2e

os: linux
os: osx

on:
  branch: master